# Generated by Django 3.1.1 on 2020-11-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201121_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dateofbirth',
            old_name='dob',
            new_name='dateofbirth',
        ),
    ]
