# Generated by Django 3.1.1 on 2020-11-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201122_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='is_C',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profession',
            name='is_Cpp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profession',
            name='is_Csharp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profession',
            name='is_Dart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profession',
            name='is_Go',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profession',
            name='is_JavaScript',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profession',
            name='is_Kotlin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profession',
            name='is_PHP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profession',
            name='is_R',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profession',
            name='is_Ruby',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profession',
            name='is_Swift',
            field=models.BooleanField(default=False),
        ),
    ]
