# Generated by Django 3.1 on 2020-10-21 08:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201021_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 8, 5, 21, 386169, tzinfo=utc)),
        ),
    ]
