# Generated by Django 3.1 on 2020-12-16 03:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201129_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='active_status',
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 3, 56, 47, 543804, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 3, 56, 47, 556294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 3, 56, 47, 548736, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 3, 56, 47, 555342, tzinfo=utc)),
        ),
    ]
