# Generated by Django 3.1 on 2020-11-15 04:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201115_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 4, 47, 8, 540812, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 4, 47, 8, 544582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 4, 47, 8, 544124, tzinfo=utc)),
        ),
    ]
