# Generated by Django 3.1 on 2020-11-10 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201110_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcomment',
            name='comment_tag',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 7, 23, 47, 987033, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tag',
            field=models.CharField(default='wOLnp7', max_length=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 7, 23, 47, 975847, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 7, 23, 47, 990013, tzinfo=utc)),
        ),
    ]
