# Generated by Django 3.1 on 2020-11-13 03:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201113_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='post_num',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 3, 21, 36, 138858, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 3, 21, 36, 137143, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 3, 21, 36, 138436, tzinfo=utc)),
        ),
    ]
