# Generated by Django 3.1 on 2020-11-10 08:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201110_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 8, 1, 56, 843654, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tag',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 8, 1, 56, 842426, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 8, 1, 56, 843133, tzinfo=utc)),
        ),
    ]
