# Generated by Django 3.1 on 2020-11-13 05:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201113_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post_num',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 5, 46, 48, 635657, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 5, 46, 48, 633863, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 5, 46, 48, 635238, tzinfo=utc)),
        ),
    ]
