# Generated by Django 3.1 on 2020-11-13 06:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201113_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='post_num',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 6, 7, 7, 296627, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 6, 7, 7, 294842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 6, 7, 7, 296187, tzinfo=utc)),
        ),
    ]
