# Generated by Django 3.1 on 2020-11-13 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20201113_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 14, 4, 16, 944653, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 14, 4, 16, 940249, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 14, 4, 16, 943936, tzinfo=utc)),
        ),
    ]
