# Generated by Django 3.1.1 on 2020-11-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_coverimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverimage',
            old_name='image',
            new_name='cover_image',
        ),
    ]
