# Generated by Django 3.1.1 on 2020-11-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20201108_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(default='default2.jpg', upload_to='cover_image'),
        ),
        migrations.DeleteModel(
            name='CoverImage',
        ),
    ]
