# Generated by Django 3.1.1 on 2020-11-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20201108_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='formal_image',
            field=models.ImageField(default='default2.jpg', upload_to='formal_image'),
        ),
    ]
